### ISSUE TITLE
"Contributor" is mapped to nothing in Zotero RIS export

### ISSUE THREAD

**Issue by dbs** [dbs/ris2web#18]
Picking up from issue #9 we have a case where the "Contributor" field in Zotero is coming up marked as ... nothing at all in the corresponding RIS output, which is what we depend upon for populating our online bibliography.

For now, I'll try creating a local modification to the Zotero RIS export, with the possibility of contributing that back to Zotero proper.

**Comment by LBST** [comment]
A word of explanation: I used "contributor" for those who had contributed to book chapters without being credited as co-author. "With" is the attribution that one often sees.

**Comment by dbs** [comment]
I've opened https://github.com/zotero/translators/pull/895 to offer a fix for upstream Zotero. In the meantime, I'll use that to support the contributor field locally.

**Comment by dbs** [comment]
Of possible interest is the comment from a Zotero contributor who believes that, based on your example, Roth et al should simply be listed as authors in Zotero: https://github.com/zotero/translators/pull/895#issuecomment-107689501
