### ISSUE TITLE
Series titles/Publication

### ISSUE THREAD

**Issue by LBST** [dbs/ris2web#21]
"Past CCLH Publications" is listed on the LI home page as a "publication," but it is catalogued under series in Zotero.  I also see a number of book titles for which I wrote chapter abstracts that are listed as "publication."  Example: Precarious Employment: Understanding Labour Market Insecurity in Canada. 

dm

**Comment by dbs** [comment]
Hmm. The RIS format bites me again. In this case, when we're describing a Book, the T2 (second title) represents the series title, but when we're describing a Chapter, the T3 (third title) represents the series title. And my simplistic query was just treating all T2 and T3 the same for summary purposes. I'll see if I can make that simplistic query a little less simplistic.
