### ISSUE TITLE
Display authors in individual records

### ISSUE THREAD

**Issue by LBST** [dbs/ris2web#42]
Bonjour, 

Can we display the authors/editors for individual records with the next update. Do a search for author Joan Sangster. All of the pertinent info displays for each record, except author. 

dm

**Comment by dbs** [comment]
Yes, this was working--of course we want to display authors, editors, translators, etc!--but appears to be a regression. The relevant code is at https://github.com/dbs/ris2web/blob/master/templates/citation.html#L41

I'll see what I can do to get that working again.
