### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by LBST** [dbs/ris2web#51]
Same old thing. The certificate has expired so when I try to go to the site it says my connection is not private. I also sent a gmail about this last night. I was hoping to mention the site at the CAWLS AGM later today if possible. Best, Desmond.

**Comment by dbs** [comment]
All should be well again, thanks to another manual restart (sigh).

**Comment by dbs** [comment]
I have also (finally) added an automatic "clean cache and restart the webserver" job to run every Sunday morning, which should prevent the need for manual restarts in the future.
