### ISSUE TITLE
No differentiation between Editors and Authors

### ISSUE THREAD

**Issue by LBST** [dbs/ris2web#9]
When creating a record, Zotero allows you to click on a variety of options under author : author, book author, editor, series editor, contributor, and translator. I have a chosen "editor" any number of times when doing book chapters, so that the book's editor is differentiated from the author of the chapter. However, the editors are all surfacing in the index as "author," which is incorrect. Is there a way to remedy this?

**Comment by dbs** [comment]
If you can give me an example, I'll see what I can do. The RIS output certainly appears to be munging them all as "author", though :/

**Comment by dbs** [comment]
Ah, here we go: https://www.zotero.org/support/kb/field_mappings says that editors come out as "A2" entires. I had been using http://en.wikipedia.org/wiki/RIS_%28file_format%29 as a guide for interpreting the RIS format, but should have been using http://refdb.sourceforge.net/manual/ch07.html#sect1-ris-format which says "A2 is a synonym for ED".

This should be a pretty easy fix.

**Comment by LBST** [comment]
That's wikipedia for you! ...I also had listed various "contributors" but they are not showing up either. dm

**Comment by dbs** [comment]
The fix that I pushed differentiates editors, series editors, and translators. Were there any other kinds of contributors that you can remember identifying?

**Comment by LBST** [comment]
The only other one was "contributor." See the book: Hidden Knowledge:
Organized Labour in the Information Age.

dm

**Comment by dbs** [comment]
I opened issue #18 to track the "Contributor" issue, which is a larger & different problem.
